### ISSUE TITLE
Add support for model ensembles / stacking in [fitted|predicted]_samples

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#102]
Might be nice to have syntax along these lines:

```r
df %>%
  add_predicted_samples(ensemble(m1, m2, m3))
```

(or maybe `stack()`?)

**Comment by tmastny** [comment]
I think choosing `ensemble` vs. `stack` depends on what you want the function to do.

I usually think of ensemble (especially in the Bayesian world) as Bayesian model averaging. This is how McElearth uses the term in his book.

I think of stacking in terms of machine learning. In particular, modeling off the predictions from the out of fold samples.

Basically, the difference between these two diagrams.

Ensemble (bayesian) model averaging:
![image](https://user-images.githubusercontent.com/20732748/37568608-72d7e2dc-2aa5-11e8-9fac-bc26f7f945c5.png)

Stacking:
![image](https://user-images.githubusercontent.com/20732748/37568610-7aca0f7e-2aa5-11e8-9837-b56b203acb21.png)

**Comment by mjskay** [comment]
Hmm, I was thinking of "stacking" as used here, which is used in the model averaging sense: https://arxiv.org/abs/1704.02030

This is the default weighting approach used by loo::model_weights :

http://mc-stan.org/loo/reference/model_weights.html

Which is probably what this function would use under the hood (ie. By default call to loo with a parameter determining the method to calculate weights, but also allow the user to input their own weights if desired). 

Maybe the right approach is to come up with something less overloaded like `model_average()` or `weighted_model()` or something like that.

I need to explore the loo interface more for this as well. It's possible the easiest approach is to find an object type it already produces and just make add_[fitted|predicted]_samples support that

**Comment by tmastny** [comment]
Thanks for the references. In this case, I think Yao et. al. is talking about about the same type of stacking I was thinking of:
>In the first, baseline-level, step, each model is fitted separately and the leave-one-out (LOO) predictor obtained for each model k and each data point i

That is awesome, I wasn't aware of Bayesian stacking techniques.

**Comment by mjskay** [comment]
I think the right way to handle this is by creating the ensemble with appropriate tools (loo?) then using `add_draws()` or what have you. Else the APIs just get duplicated all on here too.
