### ISSUE TITLE
Possible nesting syntax for [gather|spread]_samples

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#104]
In trying to write code that manipulates samples of matrices, I'm beginning to think there needs to be a list-column type of syntax that nests variables in a data frame of samples using their original shape (e.g. extracting samples from a correlation matrix as a list column where each row contains a matrix).

Syntax could be something like:

```r
m %>%
  spread_samples(nest(Rho[,]))
```

Or maybe:

```r
m %>%
  spread_samples(list(Rho[,]))
```

Or maybe less explicit (not sure if good idea?):

```r
m %>%
  spread_samples(list(Rho))
```

Or maybe just something that does it with everything automatically (I can't decide how useful this would be, so would maybe need an example use case before bothering to implement):

```r
m %>%
  nest_samples()
```

(one question for that syntax is: would it be everything nested as single-row data frames within one column, or multiple list columns? use cases would help decide)

Another option with the list() or nest() syntax would be to allow the normal indexing syntax of spread_samples to still work, so if someone had say an array of matrices (would that ever be useful?) and some other variable that uses the same index these could be lined up (where omitted indices are nested):

```r
m %>%
   spread_samples(a[i], nest(array_of_matrices[i,,]))
```

Or something like that. Again a use case for that might help decide.

Low-hanging fruit here though is definitely the basic `nest()` / `list()` support to make handling correlation matrices easier.

**Comment by alexpghayes** [comment]
Stopping by after seeing the great `spread_samples` examples from your comment in `broom.mixed`. I'm not sure how closely you follow `dplyr` development, but currently there's [lots of work](https://github.com/tidyverse/dplyr/issues/3630) on hierarchical data structures within data frames and tibbles. Not sure the time frame on those making it into `dplyr`, but I suspect the resulting helpers for heirarchical dataframes may be useful to you.

**Comment by mjskay** [comment]
Oh yeah, this looks great! Thanks for pointing me to it. I will probably wait on this issue to see where dplyr goes with matrix support, because that would be an obvious target output format.

**Comment by mjskay** [comment]
A provisional implementation of this now exists using syntax like `spread_draws(x[.,.])`. See #154.
