### ISSUE TITLE
Support for emmeans and MCMCglmm?

### ISSUE THREAD

**Issue by diogoprov** [mjskay/tidybayes#120]
I'm trying to use the package to calculate contrasts, following the tutorial [here](https://mjskay.github.io/tidybayes/articles/tidybayes.html#compatibility-with-other-packages)

```
model1 %>%
+   pairs(emmeans(~ type_arena | type_stimulus)) %>%
+   gather_emmeans_draws() %>%
+   ggplot(aes(x = .value, y = contrast)) +
+   geom_halfeyeh()
```

But I keep getting the error below: 

```
Error in as.data.frame.default(x) : 
  cannot coerce class ‘"MCMCglmm"’ to a data.frame
```

No matter I changed the syntax: 

```
model1 %>%
+   emmeans( ~ type_arena | type_stimulus) %>%
+   contrast(method = "pairwise") %>%
+   gather_emmeans_draws() %>%
+   median_qi()
```

The error persists: 

```
Error in attr(data, "call") <- object$Fixed : 
  attempt to set an attribute on NULL
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed
```

Is this a problem with emmeans or tidybayes?

**Comment by mjskay** [comment]
I take it from our twitter conversation that you figured this out, but just in case others come along to this issue and are wondering, when using MCMCglmm models with emmeans you have to pass the original data used to fit the model into emmeans, like so:

```r
# I am re-using the ABC dataset from vignette("tidybayes") here. ABC is a tibble,
# which MCMCglmm does not support unless we convert it into a data.frame
m_glmm = MCMCglmm(response ~ condition, data = as.data.frame(ABC))

m_glmm %>%
  # NOTE the use of the `data` argument on the next line: this is
  # necessary with MCMCglmm but not with rstanarm
  emmeans( ~ condition, data = ABC) %>%
  contrast(method = "pairwise") %>%
  gather_emmeans_draws() %>%
  ggplot(aes(x = .value, y = contrast)) +
  geom_halfeyeh()
```

![image](https://user-images.githubusercontent.com/6345019/43930683-bf69e3b4-9c08-11e8-8a01-c512848a389c.png)

**Comment by diogoprov** [comment]
Thanks a lot! I'll try it out and let you know if it works.

**Comment by diogoprov** [comment]
Yes, It worked. Thank you!
