### ISSUE TITLE
NA handling in point_interval 

### ISSUE THREAD

**Issue by awellis** [mjskay/tidybayes#123]
In the following example, `point_interval()` fails because the `quantile` function is called without the argument `na.rm = TRUE`

`> sample(x = c(rnorm(100), NA), size = 100, replace = TRUE) %>% 
      point_interval()
` 

`Error in quantile.default(x, c(lower_prob, upper_prob)) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
`

**Comment by mjskay** [comment]
Ah, good point. Can you say a little more about your use case for passing `NA`s to `point_interval`, so that I can get a sense of what a good solution would be? 

I ask because when using `point_interval` on a posterior sample I would not have expected `NA`s to ever happen, so failing loudly for that use case might be desirable. On the other hand, there might be good rationale for doing something like adding an `na.rm` argument to `point_interval` to allow people to circumvent the default behavior when needed, rather than having the default be to ignore `NA`s. The right solution depends on the expected frequency of different use cases.

**Comment by awellis** [comment]
Hi, 

I am using `point_interval()` to summarise posterior predictions of a rather exotic drift diffusion model (wiener distribution in stan) to fit reaction times and choices. I am basically trying to rewrite [this approach](http://singmann.org/wiener-model-analysis-with-brms-part-ii/) using `tidybayes`.

 Some subjects made very few errors, and in some conditions, there were no errors (making this a very poor data set for a DDM). Therefore, there are no reaction times for error responses.

Nevertheless, I am attempting to fit the model, and my model predicts that these subjects make zero errors in some conditions. That is the source of the problem.

It would be rather useful if I could pass the `na.rm` argument to the `quantile` function.

**Comment by awellis** [comment]
Here is a code example:
`
preds <- fit$data %>% 
    select(id, condition) %>% 
    add_predicted_draws(fit, negative_rt = TRUE, n = 200) 

preds <- preds %>% 
    mutate(decision = ifelse(.prediction > 0, 1, 0)),
           rt = abs(.prediction))

preds %>% 
    group_by(id, condition, .draw) %>% 
    summarise(prob_correct = mean(decision == 1),
              median_correct = median(rt[decision == 1]),
              median_error = median(rt[decision == 0])) %>% 
    group_by(id, condition) %>% 
    median_qi(.width = c(.50, .80, .95))
`

**Comment by mjskay** [comment]
Cool, that makes sense. I've updated `point_interval` such that it has the following behavior:

- by default, if `NA`s are present, the point summary and interval endpoints are all `NA`
- if you pass `na.rm = TRUE`, `NA`s will be stripped before points and intervals are calculated.

For example:

```r
> mean_qi(data.frame(x = c(0:10, NA)))
##    x .lower .upper .width .point .interval
## 1 NA     NA     NA   0.95   mean        qi
> mean_qi(data.frame(x = c(0:10, NA)), na.rm = TRUE)
##   x .lower .upper .width .point .interval
## 1 5   0.25   9.75   0.95   mean        qi
```

That update is on the `master` branch on Github now.

**Comment by awellis** [comment]
Thanks, works perfectly
