### ISSUE TITLE
continuous fill for geom_halfeyeh()

### ISSUE THREAD

**Issue by ASKurz** [mjskay/tidybayes#136]
I'd like to use `ggplot(aes(fill = x))` for `geom_halfeyeh()`. Take the example from your [brms tutorial](https://mjskay.github.io/tidybayes/articles/tidy-brms.html). 

```{r}
library(tidyverse)
library(brms)
library(tidybayes)

set.seed(5)
n = 10
n_condition = 5
ABC =
  data_frame(
    condition = rep(c("A","B","C","D","E"), n),
    response = rnorm(n * 5, c(0,1,2,1,-1), 0.5)
  )

m = brm(response ~ (1|condition), data = ABC, control = list(adapt_delta = .99),
  prior = c(
    prior(normal(0, 1), class = Intercept),
    prior(student_t(3, 0, 1), class = sd),
    prior(student_t(3, 0, 1), class = sigma)
  ))
```

I'd like to plot the results with `geom_halfeyeh()` such that the density fills vary continuously based on where they are along the x axis. Yet when I try this, I come up default gray.

```{r}
m %>%
  spread_draws(b_Intercept, r_condition[condition,]) %>%
  mutate(condition_mean = b_Intercept + r_condition) %>%

  ggplot(aes(y = condition, x = condition_mean, fill = condition_mean)) +
  geom_halfeyeh()
```

Am I missing something simple?

**Comment by Ax3man** [comment]
Gradient fills are not directly supported in any ggplot geoms. But the ridgeline package does add continuous fills to these sort of plots, and can be used to get your required plot manually.

**Comment by ASKurz** [comment]
Thought about it a bit and found an easy workaround:

```{r}
m %>%
  spread_draws(b_Intercept, r_condition[condition,]) %>%
  mutate(condition_mean = b_Intercept + r_condition,
         mean           = mean(condition_mean)) %>% 

  ggplot(aes(x = condition_mean, y = reorder(condition, condition_mean))) +
  geom_halfeyeh(aes(fill = mean))
```

**Comment by mjskay** [comment]
Ah --- I had thought you meant something like these:

![image](https://user-images.githubusercontent.com/6345019/48593575-5688e100-e91b-11e8-8fb8-945dee973484.png)

(from [here](https://github.com/mjskay/uncertainty-examples/blob/master/multivariate-regression.md))

which are just a `ggridges::geom_density_ridges_gradient()` plus a `tidybayes::stat_pointintervalh()`

Originally I was thinking these would have to be separate geoms, and my answer would have been something like "this kind of thing is best done by combining other geoms". But it occurs to me that I could probably finagle it to behave differently depending on data type (numeric versus categorical), and that this shouldn't have any weird knock-on effects. 

So, I'm going to reopen this. Probably I won't get to it until I start on #84; in the mean time, you can get the gradient approach by combining `geom_density_ridges_gradient` with `stat_pointintervalh`.

**Comment by ASKurz** [comment]
Yeah, I was thinking lower-tech. Thanks for reconsidering it, though.

**Comment by mjskay** [comment]
This is coming as a part of the meta_geom overhaul! (yay!). It now works on the `meta_geom` branch using `aes(fill = stat(x))` or `aes(fill = stat(y))` (depending on the orientation of the geom you are using).

Thresholds also work (e.g. `aes(fill = stat(x < 0))`). Could probably use this for ROPEs too by employing `cut(x, ...)` or the like...

**Comment by ASKurz** [comment]
In your documentation (e.g., [here](https://mjskay.github.io/ggdist/articles/slabinterval.html#highlighting-and-other-combinations)), I see how you can fill by simple uses of `fill = stat()`, particularly when using a simple criterion like `x < 0`. Is there a way, with this method, or another I haven't though of, to fill by quantiles, perhaps as defined with the `.width` argument? Something like this: 
<img width="833" alt="Screen Shot 2020-09-02 at 11 37 49 AM" src="https://user-images.githubusercontent.com/19917004/92011588-e70efc00-ed10-11ea-8b2a-dabe3b27af5b.png">

**Comment by ASKurz** [comment]
I can kinda do this with **ggridges**, but it's hacky and I'm not sure how this approach would lend itself to a nice legend key. As far as I can tell, the `bayesplot::mcmc_areas()` function won't quite do the job, either.

<img width="1699" alt="Screen Shot 2020-09-02 at 4 14 20 PM" src="https://user-images.githubusercontent.com/19917004/92037630-b1313e00-ed37-11ea-9971-841d500c67f1.png">

**Comment by mjskay** [comment]
You can do it with the `stat_dist_` family, which now exposes `pdf` and `cdf` as aesthetics, along with `cut()`. I won't pretend the spec is obvious:

```r
widths = c(.5, .8, .95)

tibble(x = dist_normal(0, 1)) %>%
  ggplot(aes(dist = x, y = "a")) +
  stat_dist_halfeye(aes(
    fill = stat(cut(abs(1 - cdf*2), breaks = c(0, widths, 1), labels = c(widths, 1), include.lowest = TRUE))
  )) +
  scale_fill_brewer(direction = -1)
```
![image](https://user-images.githubusercontent.com/6345019/92038230-10478080-ed41-11ea-9e08-dd6ae117b915.png)

I would probably wrap that up in a function (actually, given this use case I would consider adding a function like this to ggdist):

```r
cut_cdf = function(p, .width = c(0.5, 0.8, 0.95)) {
  .width = sort(.width)
  cut(abs(1 - p*2), breaks = c(0, .width, 1), labels = c(.width, 1), include.lowest = TRUE, ordered_result = TRUE)
}
```

Then you can write:

```r
tibble(x = dist_normal(0, 1)) %>%
  ggplot(aes(dist = x, y = "a")) +
  stat_dist_halfeye(aes(fill = stat(cut_cdf(cdf)))) +
  scale_fill_brewer(direction = -1)
```
![image](https://user-images.githubusercontent.com/6345019/92038352-4127b580-ed41-11ea-966a-e21284fe6f5a.png)

Although the legend has some oddities (the 1 and the NA --- the NA appears to be a bug in ggdist I'll have to fix, the 1 can be dropped by providing an upper width that covers the full extent of the mass that is visualized, like .999, and/or adjusting the p_limits argument on stat_dist).

When the second part of https://github.com/mjskay/ggdist/issues/11 is implemented, you will be able to do this on stat_halfeye and the other non-dist geoms as well.

**Comment by ASKurz** [comment]
Great, so at the moment we're limited to implementing this with the `stat_dist_` family, but it will eventually be possible with `stat_halfeye()` and friends when [https://github.com/mjskay/ggdist/issues/11](https://github.com/mjskay/ggdist/issues/11) is done. I'm excited!

**Comment by mjskay** [comment]
@ASKurz this should be working on the master branch now. E.g.:

```r
set.seed(1234)
data.frame(x = rnorm(2000, c(1,2), c(1,2)), y = c("a","b")) %>%
  ggplot(aes(x, y)) +
  stat_halfeye(
    aes(fill = stat(cut_cdf_qi(cdf, .width = c(.80, .95, .99), labels = scales::percent_format(accuracy = 1)))), 
    slab_color = "steelblue4",
    # setting trim = FALSE may or may not be desirable (I prefer trim = TRUE, which is the default,
    # since it doesn't draw anything beyond the data), but I added it to mimic your example
    trim = FALSE
  ) +
  scale_fill_brewer(direction = -1, na.translate = FALSE) +
  labs(fill = "Intervals")
```
![image](https://user-images.githubusercontent.com/6345019/100056061-ff178880-2df2-11eb-924d-fa19aae6746e.png)

See here: https://mjskay.github.io/ggdist/articles/slabinterval.html#densities-filled-according-to-intervals

**Comment by ASKurz** [comment]
Spectacular!

**Comment by ASKurz** [comment]
Okay, based on recent updates to **ggdist** (!!!), I can now pretty faithfully recreate the desired plotting theme (which has its origins in Section 16.2 of Wikle’s text, https://clauswilke.com/dataviz/visualizing-uncertainty.html#visualizing-the-uncertainty-of-point-estimates). I’m wondering if my implementation is unnecessarily clunky, though. Here’s the current challenge:

I want the fill to be semitransparent, but I want the slab_line at the top (I’m not quite sure on the proper name for that) and the brown median dot at the bottom to be solid. As far as I can tell, the alpha parameters in `stat_halfeye()` still yoke the fill with the “slap_line”. Also, I don’t want the orange point-interval or the "slab_line" to make their way into the legend key. I only want the key to depict the fill.

My solution is to break up a single `stat_halfeye()` statement into `stat_slab()` and `stat_halfeye(fill = NA)`. Is there functionality I’m missing that would make this my code less hacky?

```{r}
# load
library(tidyverse)
library(ggdist)

# reproduce Matt's data
set.seed(1234)
data.frame(x = rnorm(2000, c(1,2), c(1,2)), y = c("a","b")) %>%
  
  ggplot(aes(x, y)) +
  # fill
  stat_slab(aes(fill_ramp = stat(
    cut_cdf_qi(cdf, 
               .width = c(.8, .95, .99),
               labels = scales::percent_format(accuracy = 1)))), 
    height = 1.25, slab_alpha = .75, fill = "steelblue4") +
  # slat_line and brown dot
  stat_halfeye(.width = 0, height = 1.25,
               size = 6, slab_size = 1/2,
               slab_color = "steelblue4", fill = NA, color = "chocolate3") +
  scale_fill_ramp_discrete(range = c(1, .4), na.translate = F) +
  # customize the guide settings
  guides(fill_ramp = 
           guide_legend(
             direction = "horizontal",
             keywidth = unit(0.925, "cm"),
             label.hjust = 0.5,
             label.position = "bottom",
             title = "posterior prob.",
             title.hjust = 0.5,
             title.position = "top")) +
  # adjust the theme
  cowplot::theme_minimal_hgrid() +
  theme(legend.background = element_rect(fill = "white"),
        legend.position = c(.81, .21),
        legend.text = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")),
        legend.title = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")))
```

<img width="917" alt="Screen Shot 2021-01-06 at 10 25 47 AM" src="https://user-images.githubusercontent.com/19917004/103793304-9b939400-5009-11eb-8591-0edbdbf0a49c.png">

**Comment by mjskay** [comment]
Hmm. You can kinda do it with one by using `override.aes` in `guide_legend()` to fix the legend issues. Only thing I think this doesn't address is the issue with `alpha`, which would require you to add an extra geom:

```r
ggplot(df, aes(x, y)) +
  # fill
  stat_halfeye(aes(
      fill_ramp = stat(
        cut_cdf_qi(cdf,
               .width = c(.8, .95, .99),
               labels = scales::percent_format(accuracy = 1)))
    ),
    height = 1.25,
    .width = 0,
    size = 6,
    slab_size = 1/2,
    slab_color = "steelblue4",
    fill = "steelblue4",
    slab_alpha = 0.75,
    color = "chocolate3"
  ) +
  scale_fill_ramp_discrete(range = c(1, .4), na.translate = F) +
  # customize the guide settings
  guides(fill_ramp = 
           guide_legend(
             direction = "horizontal",
             keywidth = unit(0.925, "cm"),
             label.hjust = 0.5,
             label.position = "bottom",
             title = "posterior prob.",
             title.hjust = 0.5,
             title.position = "top", override.aes = list(color = NA, slab_color = "white"))) +
  # adjust the theme
  cowplot::theme_minimal_hgrid() +
  theme(legend.background = element_rect(fill = "white"),
        legend.position = c(.81, .21),
        legend.text = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")),
        legend.title = element_text(margin = margin(-0.2, 0, -0.2, 0, "cm")))
```
![image](https://user-images.githubusercontent.com/6345019/103842850-bf37f800-5064-11eb-8e2c-a187c11ed247.png)

Honestly this is such a customized construct I'm not sure what is gained by fitting everything into a single geom, given that both are similarly complex. I might look into allowing alpha to not overwrite fill/color-level alphas, so that you would be able to use `scales::alpha()` to adjust the fill-level alpha separately from the color-level alpha, though I'm not sure it would be less complex than the two-geom approach. See new issue here: https://github.com/mjskay/ggdist/issues/47

**Comment by ASKurz** [comment]
That makes sense. Thanks for your thoughts and for opening the new issue! I'm mainly just tickled pink I can finally make the plot.

**Comment by mjskay** [comment]
Yay! I'm glad :) :)
