### ISSUE TITLE
add_finite_sd_draws or add_banova_draws

### ISSUE THREAD

**Issue by jebyrnes** [mjskay/tidybayes#137]
I've been greatly intrigued by the BANOVA-esque concept from [Gelman's 2005 paper](http://www.stat.columbia.edu/~gelman/research/published/AOS259.pdf) and it's wonderful if bespoke implementation in the flutterbys tutorials such as [this one on ANOVA](http://www.flutterbys.com.au/stats/tut/tut7.4b.html)

I've been wondering where it might fit into the R ecosystem (I know, there's a BANOVA package, but it depends on HLMs and JAGS) and popped up an example. I've been wondering

1. Is there any easy way to automate like the standard `anova` function for the flavors of packages served here?
2. If not, where should the home for this be? Maybe something package-specific in `brms`? Perhaps it's easier to automate there already?
3. If it should be here, and there's a way to automate it, what should the output/functions look like?

```
library(brms)
library(tidybayes)
library(tibble)
library(dplyr)
library(purrr)
library(tidyr)


mt_mod <- brm(mpg ~ hp + factor(gear) + factor(carb),
              data = mtcars)

add_residual_draws <- function(mod){
  add_predicted_draws(mod, newdata = mod$data) %>%
    ungroup() %>%
    mutate(.residual = .prediction - .[[1]]) %>%
    select(-.prediction)
  
}


mt_coefs <- as_tibble(mt_mod)
my_residuals <- add_residual_draws(mt_mod)

finite_pop_sd_tibble <- tibble(
  gear_sd = mt_coefs %>% select(contains("gear")) %>% rowwise %>% apply(1, sd),
  carb_sd = mt_coefs %>% select(contains("carb")) %>% rowwise %>% apply(1, sd),
  hp_sd =  abs(mt_coefs %>% select(contains("hp")) %>% pull * sd(mtcars$hp)),
  residual_sd = my_residuals %>% group_by(.draw) %>% summarize(.sd = sd(.residual)) %>% pull
)


library(ggplot2)
ggplot(finite_pop_sd_tibble %>% gather(type, .sd),
       aes(y = type, x = .sd)) +
  geom_halfeyeh()

broom::tidyMCMC(finite_pop_sd_tibble, conf.int=TRUE, conf.level = 0.8,
                  conf.method="HPDinterval", estimate.method="median")


broom::tidyMCMC(finite_pop_sd_tibble/rowSums(finite_pop_sd_tibble)*100, conf.int=TRUE, conf.level = 0.8,
                conf.method="HPDinterval", estimate.method="median")

```

![image](https://user-images.githubusercontent.com/757410/48437512-81bed500-e74f-11e8-88df-db1625cd83d7.png)

```

> broom::tidyMCMC(finite_pop_sd_tibble, conf.int=TRUE, conf.level = 0.8,
+                 conf.method="HPDinterval", estimate.method="median")
# A tibble: 4 x 5
  term        estimate std.error conf.low conf.high
  <chr>          <dbl>     <dbl>    <dbl>     <dbl>
1 gear_sd         1.80     1.41   0.00261      3.20
2 carb_sd         3.37     1.51   1.45         5.04
3 hp_sd           2.08     1.35   0.0691       3.41
4 residual_sd     4.21     0.684  3.37         5.04
> 
> 
> broom::tidyMCMC(finite_pop_sd_tibble/rowSums(finite_pop_sd_tibble)*100, conf.int=TRUE, conf.level = 0.8,
+                 conf.method="HPDinterval", estimate.method="median")
# A tibble: 4 x 5
  term        estimate std.error conf.low conf.high
  <chr>          <dbl>     <dbl>    <dbl>     <dbl>
1 gear_sd         15.4      8.66     2.06      25.5
2 carb_sd         28.9     11.0     16.0       44.6
3 hp_sd           18.3      9.44     3.39      29.2
4 residual_sd     36.0      7.69    26.4       46.0
> 

```

**Comment by paul-buerkner** [comment]
I am not particularly motivated to implement something ANOVA like in brms, but I wouldn't complain if some post-processing package would support it.

**Comment by jebyrnes** [comment]
Cool - figured as much - any suggestions on how to work with the object structure of a brmsfit object, at least, to do this cleanly? Then I can move on to rstanarm and others....

**Comment by paul-buerkner** [comment]
What you did above didn't look bad for me. Or did you want me to look at one something specific?

**Comment by jebyrnes** [comment]
I mean, this is good for one example - I'm wondering if there's a way to wrap this in a more generic function where you don't need to a priori know a) whether you're dealing with factors or continuous variables and b) will automate going through them. Heck, I've already found one mistake in the above code due to non-automation.


so, add_finite_sd_draws or something?

________________________________

**Comment by paul-buerkner** [comment]
There surely is a way to automate that more. 

(a) One way would be to check the data frame in `brmsfit$data` for factors an only select those. Better yet, search for factors, characters or logical as they all behave like factors in `model.matrix`.

(b) Loops would surely help but they don't play so well with tidyverse. You could use perhaps use the **purrr** package for that purpose.

But I had to dive in much more into these methods to give you any really helpful advice, sorry...

One more note I do have: please don't use `factor()` or `as.factor()` in model formulas. Rather, convert variables to factors beforehand.

**Comment by jebyrnes** [comment]
Agreed on the above - it was a quick and dirty model! HA!

BTW: Corrected code for above...

```
finite_pop_sd_tibble <- tibble(
  gear_sd = mt_coefs %>% select(contains("gear")) %>% mutate(zeros = 0) %>% rowwise %>% apply(1, sd),
  carb_sd = mt_coefs %>% select(contains("carb")) %>% mutate(zeros = 0)  %>% rowwise %>% apply(1, sd),
  hp_sd =  abs(mt_coefs %>% select(contains("hp")) %>% pull * sd(mtcars$hp)),
  residual_sd = my_residuals %>% group_by(.draw) %>% summarize(.sd = sd(.residual)) %>% pull
)
```

**Comment by jebyrnes** [comment]
Q: Does brms automagically add "factor" to all factor/characters?

**Comment by paul-buerkner** [comment]
brms behaves the same as other model fitting functions that use model.frame.
That is, it keeps the class of the variable.

Am Di., 13. Nov. 2018 um 22:00 Uhr schrieb Jarrett Byrnes <
notifications@github.com>:

**Comment by jebyrnes** [comment]
Sorry, I meant in the coefficient name.

**Comment by mjskay** [comment]
Cleaning up old issues and saw that I haven't gotten around to this --- closing for now unless someone comes back saying its a strong need :). This feels possibly a little too model-type-specific for tidybayes.
