### ISSUE TITLE
computing compare_level with division rather than difference

### ISSUE THREAD

**Issue by realkrantz** [mjskay/tidybayes#141]
First of all, thank you @mjskay for this [great package](https://mjskay.github.io/tidybayes/articles/tidy-brms.html#comparing-levels-of-a-factor). Very helpful and efficient.

Need help to compute `compare_level` with `division` and any other operation such as `(2*(division-1))/(2*(division-1)+1)` rather than `difference`. Not sure how to use the argument `fun` to do that, for example with this [example](https://mjskay.github.io/tidybayes/articles/tidy-brms.html#comparing-levels-of-a-factor): 

```
m %>%
  spread_draws(r_condition[condition,]) %>%
  compare_levels(r_condition, by = condition, comparison = control) %>%
  ggplot(aes(y = condition, x = r_condition)) +
  geom_halfeyeh()
```

The vignette says:

> fun | Binary function to use for comparison. For each pair of levels of by we are comparing (as determined by comparison), compute the result of this function.

But I fail to see how it could be done to get `division` or perform any other `arithmetic operation` instead of `difference`.

Thank you in advance.

**Comment by mjskay** [comment]
The default value of fun is <code>\`-\`</code>, i.e. the subtraction operator. The cool thing about R is that all the operators (`+`, `-`, `/`, `*`, etc) in the language are actually just functions, and you can even call them as such. E.g. this:

```r
1 + 5
```
```
6
```


Can be written:

```r
`+`(1, 5)
```
```
6
```

`compare_levels` just has <code>fun = \`-\`</code> by default, i.e. it uses the subtraction function.

E.g. consider two samples from a log-normal distribution, with groups `"a"` and `"b"`:

```r
df = 
  data.frame(g = c("a", "b"), x = rlnorm(10000)) %>%
  group_by(g) %>%
  mutate(.draw = 1:n())
```

`compare_levels` by default uses subtraction (i.e. <code>\`-\`</code>):

```r
df %>%
  compare_levels(x, by = "g") %>%
  median_qi()
```
```
# A tibble: 1 x 7
  g           x .lower .upper .width .point .interval
  <fct>   <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
1 b - a 0.00725  -5.88   5.83   0.95 median qi    
```

We could specify `fun` explicitly, which would yield the same result:

```r
df %>%
  compare_levels(x, by = "g", fun = `-`) %>%
  median_qi()
```
```
# A tibble: 1 x 7
  g           x .lower .upper .width .point .interval
  <fct>   <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
1 b - a 0.00725  -5.88   5.83   0.95 median qi    
```

Or change it to something else, like `/`:

```r
df %>%
  compare_levels(x, by = "g", fun = `/`) %>%
  median_qi()
```
```
# A tibble: 1 x 7
  g         x .lower .upper .width .point .interval
  <fct> <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
1 b / a  1.01 0.0590   17.0   0.95 median qi    
```

Does that help?

**Comment by realkrantz** [comment]
That is very helpful. Thanks, @mjskay.

**Comment by ASKurz** [comment]
How would one go about using `fun` if one's desired contrast was `exp(a - b)`?

**Comment by mjskay** [comment]
> ```r
> df %>%
>   compare_levels(x, by = "g", fun = `-`) %>%
>   median_qi()
> ```

A few different ways come to mind:

1. Provide a function that does the complete calculation to `fun`, e.g. `compare_levels(..., fun = \(x, y) exp(x - y))`
2. Do <code>compare_levels(..., fun = \`-\`)</code> followed by (e.g.) `mutate()` for the exponentiation step
3. If you just want to compute one or more arbitrary expressions of some specific levels of `x`, you can provide those expressions to `comparison` as a list of unevaluated expressions using (e.g.) `rlang::exprs()`. So if `a` and `b` are levels of `"g"`, you could do something like `compare_levels(x, by = "g", comparison = rlang::exprs(exp(a - b)))` to specifically get `exp(a - b)` for the levels `a` and `b`.
