### ISSUE TITLE
See if we can reduce the number of package dependencies

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#143]
**Imports**:
- [ ]    plyr,
- [ ]    dplyr,
- [ ]    tidyr,
- [ ]    ggplot2
- [x] ~~stringi~~ --- dropped, replaced with base r
- [x] ~~stringr~~ --- dropped, replaced with base r
- [x]  ~~LaplacesDemon~~ --- dropped, replaced with better Mode implementation
- [ ]    coda,
- [ ]    purrr
- [x] ~~MASS~~ --- not used anymore
- [ ]    rlang,
- [x] ~~ggstance,~~ --- moved to suggests (geoms are no longer based on this)
- [x] ~~ggridges~~ --- moved to suggests
- [x]    ~~grid~~ --- moved to ggdist,
- [ ]    forcats,
- [x]    ~~HDInterval~~ --- moved to ggdist,
- [ ]    arrayhelpers,
- [ ]    tidyselect,
- [ ]    tibble
- [ ]    magrittr

**Suggests** (most of these will stay b/c they are packages to support):
- packages to support (therefore must be kept):
   - [x]    rstan
   - [x]    runjags,
   - [x]    rjags,
   - [x]    jagsUI,
   - [x]    rstanarm
   - [x]    emmeans,
   - [x]    MCMCglmm,
   - [x]    brms
- packages for testing (therefore must be kept):
   - [x]    testthat,
   - [x]    vdiffr,
- packages for building docs/vignettes (therefore must be kept):
   - [x]    knitr,
- other:
   - [ ]    svglite,
   - [x]    ~~ggstance~~ --- not used anymore
   - [x] ~~rstantools~~ --- not used anymore
   - [ ]    broom
   - [ ]    dotwhisker,
   - [ ]    bayesplot,
   - [ ]    modelr,
   - [ ]    cowplot,
   - [ ]    ggridges
   - [ ]    covr,
   - [ ]    gdtools,
   - [ ]    rmarkdown,
   - [ ]    ggrepel,
   - [ ]    bindrcpp

**Comment by lionel-** [comment]
> tibble --- necessary functions re-exported by dplyr

I think it's cleaner to have the explicit Import from tibble, rather than dplyr. The package still depends on tibble in both cases.

**Comment by mjskay** [comment]
oh yeah, makes sense

**Comment by mjskay** [comment]
reduced a lot of these by now. Only one remaining that is likely removable at this point is arrayhelpers; I will open a separate issue.
