### ISSUE TITLE
support bsts more explicitly in fitted_draws, predicted_draws, and/or tidy_draws

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#150]

**Comment by fja062** [comment]
Are rjags-type models supported by `add_fitted_draws` and `add_predicted_draws`?

**Comment by mjskay** [comment]
Unfortunately no --- JAGS, like Stan (as far as I am aware anyway) does not have a universal interface for generating predictions, so there isn't really a generic way to construct input for `add_fitted_draws` or `add_predicted_draws`. It depends on the model you've created.

That said, if you can construct a matrix of predictions or fits (e.g. by creating a variable in JAGS that has the predictions you want) you might be able to use [`add_draws()`](https://mjskay.github.io/tidybayes/reference/add_draws.html). I don't have an example of using `add_draws` with JAGS written up but I'll add it to my todo.

**Comment by fja062** [comment]
OK, I'll try giving the `add_draws()` suggestion a go on predictions created in jags!

**Comment by mjskay** [comment]
closing this --- `add_draws()` works pretty well for this use case, and the other new option (wrapping with `posterior::rvar()`) is also pretty good.
