### ISSUE TITLE
make compose_data create matrix data structure

### ISSUE THREAD

**Issue by realkrantz** [mjskay/tidybayes#157]
Hi, @mjskay. This issue has also been posted [here](https://stackoverflow.com/questions/54550104/creating-a-function-to-specify-a-large-predictor-matrix-for-stan-data-block). 

Essentially, given the sample data `sampleDT` below, I would like to use `compose_data` to create a data block to be used in the stan `desired data block` shown below.

**#sample data**

```
dat <- data.frame(
id = c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4),
imput = c(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5),
A = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 
B = c(1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0),
Pass = c(278, 278, 278, 278, 278, 100, 100, 100, 100, 100, 153, 153, 153, 153, 153, 79, 79, 79, 79, 79), 
Fail = c(740, 743, 742, 743, 740, 7581, 7581, 7581, 7581, 7581, 1231, 1232, 1235, 1235, 1232, 1731, 1732, 1731, 1731, 1731), 
W_1= c(4, 3, 4, 3, 3, 1, 2, 1, 2, 1, 12, 12, 11, 12, 12, 3, 5, 3, 3, 3),
W_2= c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12, 3, 3, 3, 3, 3),
W_3= c(4, 3, 3, 3, 3, 1, 2, 1, 1, 1, 12, 12, 11, 12, 12, 3, 3, 3, 3, 3),
W_4= c(3, 3, 4, 3, 3, 1, 1, 1, 2, 1, 12, 12, 13, 12, 12, 3, 2, 3, 3, 3),
W_5= c(3, 3, 3, 3, 3, 1, 0, 1, 1, 1, 12, 12, 12, 12, 12, 3, 3, 3, 3, 3),
W_6= c(4, 3, 3, 3, 3, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12, 3, 3, 3, 3, 3),
W_7= c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12, 3, 3, 3, 3, 3),
W_8= c(3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 15, 12, 12, 12, 12, 3, 3, 3, 3, 3),
W_9= c(3, 3, 3, 4, 3, 1, 1, 1, 1, 1, 12, 12, 12, 12, 12, 2, 3, 3, 3, 3),
W_10= c(3, 3, 4, 3, 3, 1, 1, 1, 1, 1, 12, 10, 12, 12, 12, 3, 3, 3, 3, 3)
      )
```

**#current data block**

```
    data{
    int N;                              // number of observations
    int ncases[N];                        // independent variable 
    int A[N];                                 // independent variable 
    int B[N];                                 // independent variable 
    int nn[N];                              // independent variable 
    int id[N];                                //individual id
    real<lower=0> w_1[N];                     //variable w_1
    real<lower=0> w_2[N];                     //variable w_2       
    real<lower=0> w_3[N];                     //variable w_3      
    real<lower=0> w_4[N];                     //variable w_4       
    real<lower=0> w_5[N];                     //variable w_5       
    real<lower=0> w_6[N];                     //variable w_6       
    real<lower=0> w_7[N];                     //variable w_7       
    real<lower=0> w_8[N];                     //variable w_8       
    real<lower=0> w_9[N];                     //variable w_9       
    real<lower=0> w_10[N];                     //variable w_10
    }
```

**#desired data block**

```
data{
int N;                              // number of observations
int ncases[N];                        // independent variable 
int A[N];                                 // independent variable 
int B[N];                                 // independent variable 
int nn[N];                              // independent variable 
int id[N];                                //individual id
int W;                                //columns of weights?
real<lower=0> weights[N, W];                  // N by W block of weights 
}
```

**#my current approach**

```
N <- nrow(dat)
ncases <- dat$Pass
nn <- dat$Fail + dat$Pass
A <- dat$A
B <- dat$B
id <- dat$id
imput <- dat$imput
w_1 <- dat$W_1
w_2 <- dat$W_2
w_3 <- dat$W_3
w_4 <- dat$W_4
w_5 <- dat$W_5
w_6 <- dat$W_6
w_7 <- dat$W_7
w_8 <- dat$W_8
w_9 <- dat$W_9
w_10 <- dat$W_10

#for current data block
    dat1 <-dat %>%compose_data(.n_name = n_prefix("N"))

#for desired data block
    dat2 <- list (N = N, ncases = ncases, A = A, B = B, id = id, P = imput, nn = nn, W = 10,
                  weights = cbind(w_1, w_2, w_3, w_4, w_5, w_6, w_7, w_8, w_9, w_10))
```

**#my problems**

(1) I fail to see how I could use  `dat1 <-dat %>%compose_data(.n_name = n_prefix("N"))` to get a list to be passed to my `desired data block`.
(2) Additionally, using  `dat2 <- list (N = N, ncases = ncases, A = A, B = B, id = id, P = imput, nn = nn, weights = cbind(w_1, w_2, w_3, w_4, w_5, w_6, w_7, w_8, w_9, w_10))` is not feasible for `weights` with `w_W`, where `W>1000`.

Thanks in advance for any help.

**Comment by mjskay** [comment]
Check out this response to #159 and let me know if it answers your question: https://github.com/mjskay/tidybayes/issues/159#issuecomment-468878638

**Comment by realkrantz** [comment]
Thanks, @mjskay. Not sure because in my case:

(1) the matrix `weights ` is made of all variables containing a given pattern (e.g., "^W_") , and 
(2) the matrix `weights ` is contained in a data frame `dat` which also contains other variables, i.e., those columns without the pattern "^W_". 

The idea would be to somehow use `compose_data` instead of 

```
w.matrix = as.matrix(dat[,grepl("^W_", colnames(dat))])
dat1 <- list (N = N, ncases = ncases, A = A, B = B, id = id, P = imput, nn = nn,
    W = ncol(w.matrix), weights = w.matrix)
```

which is desirable when working with large data frames, as in my case.

Any thoughts?

**Comment by mjskay** [comment]
Hmm, I guess I'm not sure I quite understand what you are imagining compose_data should do differently in this case. It might help to give an example of what you think the syntax could look like that would be simpler.

Currently, you have a data frame with data "in the column names". I.e., all of your `w_1`, `w_2`, etc. columns are not in a "tidy" format to begin with. `compose_data` is intended for use with tidy data, so my suggestion would be to turn the data into tidy data before passing it into `compose_data` --- e.g., turning it into a matrix or a nested column, which is exactly what you are doing here:

```
w.matrix = as.matrix(dat[,grepl("^W_", colnames(dat))])
```

Since `compose_data` now correctly supports matrix columns, you should now be able to use a column constructed in this way directly in `compose_data`. I don't immediately see a way to make this simpler, but if there's something you had in mind let me know.

**Comment by mjskay** [comment]
Closing this pending further feedback, as I think #159 solves it.

**Comment by realkrantz** [comment]
Great, @mjskay. Yes, `w.matrix = as.matrix(dat[,grepl("^W_", colnames(dat))])` along with #159 can do the job. Thanks for this.
