### ISSUE TITLE
But what about the histogram?

### ISSUE THREAD

**Issue by ASKurz** [mjskay/tidybayes#162]
Hey @mjskay,

Would it to possible to either extend `geom_halfeyeh()` or make a complimentary function that could depict the posterior as a histogram while still summarizing the central tendency and intervals below?

Thanks,
Solomon

**Comment by mjskay** [comment]
Ah interesting question. I think i would want to roll this into the general consolidation of the various density/pointinterval geoms I am planning (#84).

In the mean time, I think you could do something like this using `ggridges::geom_density_ridges(stat = "binline", ...) + stat_pointintervalh()`?

**Comment by ASKurz** [comment]
That sounds like a useful consolidation, for sure. And a big one. In the meantime, thanks for the suggestion! I’ll play around with it.

**Comment by mjskay** [comment]
You may be pleased to hear that this is available on the `meta_geom` branch now as part of the complete overhaul of the tidybayes geoms. It's not on `master` yet but it will filter down soon and will be in the next CRAN release as `stat_histinterval` and `stat_histintervalh` (unless I change the names before then...)
