### ISSUE TITLE
How to add already made predictions to data frame

### ISSUE THREAD

**Issue by PhoenixB** [mjskay/tidybayes#173]
Dear Matthey,

Is it possible to add already calculated predictions from a brms model, i.e. `pp_average.brmsfit()` in a tidy format to the original data frame circumventing `add_predicted_draws()`?

Kindest regards,
Pascal

**Comment by mjskay** [comment]
Yes, certainly! That is what [add_draws()](http://mjskay.github.io/tidybayes/reference/add_draws.html) is for. You would need to use `summary = FALSE` with `pp_average()`. Let me know if you have trouble getting it to work.

**Comment by PhoenixB** [comment]
Ah cool! This one slipped my attention! Thank you very much!
I suppose it is also possible with ordinal brms models?
