### ISSUE TITLE
Make stat_interval provide width automatically for position='dodge'

### ISSUE THREAD

**Issue by lindeloev** [mjskay/tidybayes#180]
I love `stat_interval` and would like to use it for some ordinary non-MCMC data. It says in the doc that it takes the `position` argument, but AFAICS, it does not respect it. I would expect two `stat_interval`s on this plot because of the `group`ing on `x`:

```
# Make some data which is two normals on x and bimodal on x2
df = data.frame(x = rep(c('A', 'B'), 30), 
                x2 = rep('A', 60),
                y = c(x = c(rnorm(30, 0), rnorm(30, 5))))

# Plot it, grouped by x
ggplot(df, aes(x=x2, y=y, group=x)) + 
    stat_interval(position='dodge')
```

Current result:
![image](https://user-images.githubusercontent.com/1439417/60578990-82f64e00-9d82-11e9-931f-0b6ee1e84d89.png)

So there's only one interval, and that behaves weird in the edges (here, the top).

**Comment by mjskay** [comment]
Ah, yeah, good point. A workaround is to provide the width used to calculate the dodge manually with something like `position = position_dodge(width = .1)` (adjust the width to your taste), but some reasonable width should definitely be provided automatically based on the width of the geom.

**Comment by mjskay** [comment]
TODO:

- [ ] add default width/height calculation for geom_interval(h)
- [ ] add default width/height calculation for geom_pointinterval(h) (might as well)

**Comment by mjskay** [comment]
This is now fixed in the github version. If the default spacing is not to your taste, manually specifying it using `position_dodge(width = XXX)` also works (and will already work on the current CRAN version).

**Comment by lindeloev** [comment]
Awesome, thank you!

(Don't know why I didn't see the warning about ``width` in the current CRAN version)
