### ISSUE TITLE
stat_halfeyeh -> geom_halfeyeh

### ISSUE THREAD

**Issue by osiris08** [mjskay/tidybayes#216]
Not sure if it because of @export changed, but `stat_halfeyeh` can no longer be found under the namespace `tidybayes`. With error message 'Error in stat_halfeyeh() : could not find function "stat_halfeyeh"'. However it works with `geom_halfeyeh`. 

Examples using `stat_*` functions still exist in many documentation files, including `README.md`, and other vignettes.

**Comment by mjskay** [comment]
Sorry --- this is a documentaiton issue. `stat_halfeyeh` and the like (basically everything in the slabinterval vignette) are currently only available in the github version of tidybayes. They are not on CRAN yet.

**Comment by osiris08** [comment]
Hi Matthew, thanks for explaining! and absolutely no need to apologise, I only started using the package recently, that's why I am a bit confused. But totally love it, especially those nice geoms!

**Comment by mjskay** [comment]
Thanks! :)

I'm hoping to have some time to get the newer geoms on CRAN soon :)
