### ISSUE TITLE
Predicted counts for multinomial models

### ISSUE THREAD

**Issue by IvanUkhov** [mjskay/tidybayes#219]
I have a multinomial model in `brms` and use `predicted_draws` and `add_predicted_draws` to conveniently pack together the input data and posterior draws. I was expecting to see counts for individual categories in the output, and I thought they would appear in `.prediction` next to `.category`. However, `.prediction` is always `NA`. Is there something I am missing?

```r
data <- tribble(
    ~a,   ~b,   ~c, ~total,
  3000, 3000, 7000,  13000,
)
data$counts <- with(data, cbind(a, b, c))
formula <- brmsformula(counts | trials(total) ~ 1)
fit <- brm(formula, data, multinomial(), seed = 42)
predicted_draws(fit, tibble(total = 1000))
```

**Comment by mjskay** [comment]
Ah yup I see the problem. Turns out there was a pull request with a possible solution from @aammd awhile back (#176) that I hadn't gotten around to looking at in more detail (sorry Andrew!).

This should be fixed on master now.
