### ISSUE TITLE
stat_histintervalh(), outline individual bars

### ISSUE THREAD

**Issue by ASKurz** [mjskay/tidybayes#222]
It would be handy if `stat_histintervalh()` included an aesthetic setting that controlled the outlines between the bars. See [this twitter thread](https://twitter.com/SolomonKurz/status/1222553769285758976).

**Comment by mjskay** [comment]
Yeah. The most obvious approach off the top of my head might be an option to make it so that the existing outline also goes between the bars. Would that be sufficient for your use case?

**Comment by ASKurz** [comment]
Yes. My impression is that's how the `color` argument works within `ggplot2::geom_histogram()`.

**Comment by ASKurz** [comment]
Woot!
