### ISSUE TITLE
put rethinking stuff in another package

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#26]
It can't be in this package for a cran release

**Comment by jebyrnes** [comment]
q: does tidybayes work with rethinking again? And if so, the current version, or the one coming with the new version of the book? Thanks! Been trying to see if it works with the current version, even using tidybayes.rethinking and striking out.

**Comment by mjskay** [comment]
Yeah it's presently broken (or at least I haven't touched tidybayes.rethinking in a bit).

The core tidybayes API has changed quite a bit since I wrote the rethinking version of it. To update it I'd want to translate the current implementations of tidy_link and tidy_sim into versions of fitted_draws and predicted_draws following the new tidybayes API. With my schedule this semester I probably won't have time to do that until after April at the earliest, but I would accept pull requests :-)

**Comment by mjskay** [comment]
Also it occurs to me that in the absence of working versions of fitted/predicted_draws, you should still be able to use the new add_draws function. Also, spread_draws and gather_draws should work on the underlying Stan model.

**Comment by mjskay** [comment]
Also also, the most relevant issue for tracking this is probably in the other repo, as unless/until rethinking is on cran I am keeping functions for it out of core tidybayes so that this package doesn't have non-cran dependencies (makes cran submission easier): https://github.com/mjskay/tidybayes.rethinking/issues/1

**Comment by mjskay** [comment]
To follow-up (since I hadn't actually tested this when I wrote the previous response), `tidybayes.rethinking::tidy_link()` and `tidybayes.rethinking::tidy_sim()` should work, in addition to `spread_draws` and `gather_draws`. These are the old names for `add_fitted_draws` and `add_predicted_draws`. I have only tested these on the current version, not the version for the new book.
