### ISSUE TITLE
Add fitted draws for multivariate ordinal models 

### ISSUE THREAD

**Issue by JCruk** [mjskay/tidybayes#265]
I have a hierarchical ordinal multivariate model in `brms` and would like to plot out the fitted draws and predictions. There are two response variable both on a 3-point scale.

When I use 
```
add_fitted_draws(data, mv_ord_mod)

or

add_fitted_draws(data, mv_ord_mod, dpar = TRUE)
```

I get a `.category` column representing the ordinal responses, but only a single `.value`. 

Is there a way to identify which of the response variables is being reported? Is it possible to return a `.response` column to indicate which variable each row represents?

**Comment by JCruk** [comment]
I found `add_fitted_draws` accepts "resp" as an additional argument and I can add a variable with the response name repeated.

**Comment by mjskay** [comment]
Ah glad you were able to figure it out! 

I might want to have a nicer way of doing this in the future, but I think it will wait on changes in {posterior}...

**Comment by ASKurz** [comment]
Along these lines, would it be possible to have `add_fitted_draws()` return a column specifying the response names? I'm working on a project with this exact issue--a multivariate ordinal model--and man would it be nice if this was clarified in the output.

**Comment by JCruk** [comment]
> Along these lines, would it be possible to have `add_fitted_draws()` return a column specifying the response names? I'm working on a project with this exact issue--a multivariate ordinal model--and man would it be nice if this was clarified in the output.

One approach that worked for me was to pass the `resp = "var"` argument and then add a `mutate(VarName = "Response") for each response and `rbind` them together
