### ISSUE TITLE
add_epred_draws() not exported?

### ISSUE THREAD

**Issue by bwiernik** [mjskay/tidybayes#291]
In the current github master, it seems that `tidybayes::add_epred_draws()` isn't exported, though linpred, predicted, and residuals are

**Comment by mjskay** [comment]
I'm confused... it looks like it is exported to me?

**Comment by bwiernik** [comment]
Huh, after restarting R they are showing up correctly. Should have tried that first sorry

**Comment by mjskay** [comment]
No worries
