### ISSUE TITLE
spread_draws didnt work

### ISSUE THREAD

**Issue by Taeyeon1607** [mjskay/tidybayes#296]
Hello!

I made a regression model using rstanarm, and below are the output results of get_variables and spred_draws.

> get_variables(stan_model)
[1] "(Intercept)"   "mom_iq"        "sigma"         "accept_stat__"
[5] "stepsize__"    "treedepth__"   "n_leapfrog__"  "divergent__"  
[9] "energy__"  

> stan_model %>% 
+   spread_draws("Intercept", mom_iq)
Error: `x` must be a vector

When only the mom_iq at the back is input, it is output without any abnormality,
but that intercept seems to be the problem. How can I solve this?

**Comment by mjskay** [comment]
Variables with spread_draws must be specified as bare names (ie using backticks or no quotes at all), not strings. Does this work? 

```r
stab_model %>%
  spread_draws(`(Intercept)`, mom_iq)
```

**Comment by Taeyeon1607** [comment]
Thanks for replying!

I wrote it wrongly in the text.
I entered it correctly as below and got the same error.

> stan_model %>% 
+   spread_draws('(Intercept)', mom_iq)
Error: `x` must be a vector

**Comment by mjskay** [comment]
Looks like you are using single quotes ('), not backticks (`)

**Comment by Taeyeon1607** [comment]
The problem has been resolved.

Since I'm a beginner, I'm bothered by an easy problem.

I've been struggling with this problem all day yesterday.

Thank you very much.

**Comment by mjskay** [comment]
No worries, glad it is resolved! Quoting in R can be very confusing. Apologies the error message wasn't more helpful to start with.
