### ISSUE TITLE
posterior_epred for truncated 'gen_extreme_value' models

### ISSUE THREAD

**Issue by JackCaster** [mjskay/tidybayes#307]
I am doing an extreme value theory analysis so I built a model with brms and the `gen_extreme_value` family. Specifically, I am using a truncated response distribution `brm(y | trunc(lb = 0.0) ~ ..., family = gen_extreme_value(), ...`. The sampling works but then I get the error `Error: posterior_epred values on the respone scale not yet implemented for truncated 'gen_extreme_value' models.` during postprocessing. Is this something that could be implemented in tidybayes or shall this be fixed in brms directly?

**Comment by mjskay** [comment]
Ah yeah, that's a brms issue unfortunately --- can't be fixed on the tidybayes side, which depends on `brms::posterior_epred()` having an implementation for the model in question. Sorry I can't be of more help!
