### ISSUE TITLE
`spread_draws()` with rstanarm glmer?

### ISSUE THREAD

**Issue by potash** [mjskay/tidybayes#308]
I am having trouble applying `spread_draws()` to a varying intercept varying slope model fit with the following formula and `stan_glmer()`

```
y ~ log(x) + (log(x) | site)
```

Calling get_variables() returns something like this:

```
[1] "(Intercept)"                                
[2] "log(x)"                            
[3] "b[(Intercept) site:A]"                
[4] "b[log(x) site:A]"            
[5] "b[(Intercept) site:B]"                     
[6] "b[log(x) site:B]"
...
```

Is this naming convention compatible with spread_draws()? I'd like to extract a dataframe that looks like this:

```
.draw, site,(Intercept),log(x)
1,A,...,...
1.B,...,...
...
```

**Comment by potash** [comment]
Simply spread_draws(fit, b[i,j]) works. I was backticking `b[i,j]` and that was breaking it with:

```
No variables found matching spec: b\[i\,j\]
```

Is that a bug?

**Comment by mjskay** [comment]
Yeah `b[i, j]` should work, and if you want the `i` as columns `b[i, j] | i` would do that.

Using backticks like <code>\`b[i,j]\`</code> doesn't work because that means you are asking for a variable named `"b[i,j]"` exactly.

**Comment by potash** [comment]
Ah that explains it, thanks

**Comment by mjskay** [comment]
great, happy to help!
