### ISSUE TITLE
Received error message with gather_draws and tidybayes

### ISSUE THREAD

**Issue by wleuenberger** [mjskay/tidybayes#315]
Warning message:
`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the tidybayes package.
  Please report the issue at <https://github.com/mjskay/tidybayes/issues/new>.

**Comment by mjskay** [comment]
That was fixed in tidybayes 3.0.3 --- please update (e.g. run `update.packages()`) and double check the output of `packageVersion("tidybayes")` is the latest (currently 3.0.6).
