### ISSUE TITLE
Make [spread|gather]_[predicted|fitted]_samples

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#63]
Analogous to `modelr::[spread|gather]_predictions`.

**Comment by tmastny** [comment]
Any update on this feature? Right now the pattern seems to apply `add_[predicted/fitted]_samples` and then `bind_[columns/rows]` or maybe a join. I've used this pattern [here](https://timmastny.rbind.io/blog/multilevel-mrp-tidybayes-brms-stan/) and there's your example on the README.md. 

Based on what I've learned in https://github.com/mjskay/tidybayes/pull/98 and from the [`modelr` implementation](https://github.com/tidyverse/modelr/blob/7a1270d2729da48c913732054d1cfbd185305827/R/predictions.R) I think I build something that would work, if you're still interested in the feature and wouldn't mind some more help.

**Comment by mjskay** [comment]
Yeah, I would love it if you wanted to take this on!

More generally, I wanted to say that your input has been much appreciated! I am traveling this week, hence current slow response on #98, but I should have time to look over that and merge it early next week.

**Comment by tmastny** [comment]
Sounds good, no rush. I have some extra free time these days and would be happy to help out.

**Comment by mjskay** [comment]
I feel like this feature is largely obsolete these days with a nested / map-based workflow being preferable. E.g. assuming a data frame with some models in it, something like `df %>% mutate(draws = map(model, add_fitted_draws, grid) %>% unnest()` or what have you, which is more explicit and makes it easier to apply different arguments at specific levels (e.g. arguments that vary by model could be integrated into df and then incorporated into the call using pmap, and arguments that are the same for all models would be applied directly). So making new syntax to do this seems unnecessary from both an API-complexity and maintenance perspective.

Leaving open for a little in case someone comes along with convincing arguments to the contrary.

**Comment by mjskay** [comment]
No one came along with a convincing argument, so closing this :-)
