### ISSUE TITLE
adding predicted samples after rstanarm model fails

### ISSUE THREAD

**Issue by puterleat** [mjskay/tidybayes#73]
This currently gives the error: `Error in 1:nrow(.) : argument of length 0`

```
m_mpg = stan_lm(mpg ~ hp*wt, data = mtcars, prior=R2(location=.5), chains=2, iter=1000)
newdata <- expand.grid(hp=c(50,250), wt=c(1000,3000)) %>% as_tibble()
add_predicted_samples(newdata, m_mpg)
```

This seems like a bug, because I can happily `gather_samples(m_mpg, hp)` etc.

**Comment by mjskay** [comment]
Sorry, there was a bug in add_predicted_samples that I fixed on the dev branch but had not pushed to master yet. I have done that now, so if you install the latest version from github it should be fixed now (plus I added a test to ensure it continues to work).
