### ISSUE TITLE
Which version of R is supported via Cran?

### ISSUE THREAD

**Issue by puterleat** [mjskay/tidybayes#74]
If I install with install.packages via Cran I get this:

`Warning in install.packages :
  package ‘tidybayes’ is not available (for R version 3.4.1)`

Which versions are supported, and if only very latest R is supported should this be documented?

**Comment by mjskay** [comment]
Sorry for the ambiguity --- tidybayes is not on CRAN yet, but I am preparing a submission currently. You can track the progress towards CRAN readiness using the [CRAN milestone](https://github.com/mjskay/tidybayes/milestone/1). When that reaches 100% I will submit to CRAN.

In the meantime `devtools::install_github("mjskay/tidybayes")` is the only way to install it. I've clarified that in the installation instructions.
